[phases.setup]
nixPkgs = ["nodejs_18", "python3", "php", "ruby", "go"]

[phases.install]
cmds = [
  "npm install",
  "cd client && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build || npm run build:no-lint"
]

[start]
cmd = "npm start"