[phases.setup]
nixPkgs = ["nodejs_18", "python3", "php", "ruby", "go"]

[phases.install]
cmds = [
  "npm ci --only=production",
  "cd client && npm ci --only=production"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "npm start"