[phases.setup]
nixPkgs = ["nodejs_18", "python3", "php", "ruby", "go"]

[phases.install]
cmds = [
  "npm install --omit=dev",
  "cd client && npm install --omit=dev"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "npm start"